app:
  name: "auth-service"
  version: "1.0.0"

http:
  port: "8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s

log:
  level: "debug"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "auth_db"
  ssl_mode: "disable"
  pool_size: 10

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

limiter:
  rps: 10
  burst: 20
  ttl: 10m
